const KEY='game-note-v2';
const seed=[
{id:1,name:'Roblox',tag:'RBX',progress:72,notes:[{id:11,title:"Sol's RNG",body:'Farm aura và theo dõi mốc thời gian.'}],goals:[{id:12,text:'Đạt 30M aura',done:false},{id:13,text:'180,000 phút chơi',done:false}]},
{id:2,name:'FC Mobile',tag:'FC',progress:45,notes:[{id:21,title:'Đội hình',body:'Ghi lại cầu thủ và chiến thuật.'}],goals:[{id:22,text:'Hoàn thiện đội hình',done:false}]},
{id:3,name:'Minecraft',tag:'MC',progress:30,notes:[{id:31,title:'Survival',body:'Ý tưởng base và vật liệu cần farm.'}],goals:[{id:32,text:'Xây base',done:false},{id:33,text:'Tìm Nether Fortress',done:false}]}
];
let games=load(),view='games',editingId=null;
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)?x:seed}catch{return seed}}
function save(){localStorage.setItem(KEY,JSON.stringify(games))}
function id(){return Date.now()+Math.floor(Math.random()*1000)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function render(){const q=document.getElementById('search').value.trim().toLowerCase();const list=games.filter(g=>(g.name+' '+g.tag+' '+g.notes.map(n=>n.title+' '+n.body).join(' ')+' '+g.goals.map(x=>x.text).join(' ')).toLowerCase().includes(q));if(view==='games')gamesView(list);if(view==='notes')notesView(list);if(view==='goals')goalsView(list)}
function gamesView(list){let notes=games.reduce((a,g)=>a+g.notes.length,0),goals=games.reduce((a,g)=>a+g.goals.length,0),done=games.reduce((a,g)=>a+g.goals.filter(x=>x.done).length,0);document.getElementById('content').innerHTML=`<div class="stats"><div class="stat"><b>${games.length}</b><small>Games</small></div><div class="stat"><b>${notes}</b><small>Notes</small></div><div class="stat"><b>${goals}</b><small>Goals</small></div><div class="stat"><b>${done}</b><small>Completed</small></div></div><div class="grid">${list.length?list.map(gameCard).join(''):'<div class="empty">No games found.</div>'}</div>`}
function gameCard(g){return `<article class="card"><div class="game-head"><div class="icon">${esc(g.tag)}</div><div><div class="game-name">${esc(g.name)}</div><div class="muted">${g.notes.length} notes · ${g.goals.filter(x=>x.done).length}/${g.goals.length} goals done</div></div></div><div class="progress"><div class="bar" style="width:${g.progress}%"></div></div><div class="muted">${g.progress}% progress</div><div class="card-foot"><span class="tag">${g.goals[0]?esc(g.goals[0].text):'No goal yet'}</span><div class="card-actions"><button class="mini" onclick="editGame(${g.id})">Edit</button><button class="mini" onclick="openGame(${g.id})">Open</button></div></div></article>`}
function openGame(gid){const g=games.find(x=>x.id===gid);document.getElementById('title').textContent=g.name;document.getElementById('content').innerHTML=`<div class="detail"><div class="detail-top"><div class="game-head"><div class="icon">${esc(g.tag)}</div><div><div class="game-name">${esc(g.name)}</div><div class="muted">Game workspace</div></div></div><div class="detail-actions"><button class="mini" onclick="editGame(${g.id})">Edit</button><button class="mini" onclick="deleteGame(${g.id})">Delete</button></div></div><div class="progress"><div class="bar" style="width:${g.progress}%"></div></div><div class="muted">Progress: ${g.progress}%</div><input class="range" type="range" min="0" max="100" value="${g.progress}" oninput="setProgress(${g.id},this.value)"><div class="section-head"><h2>Goals</h2><button class="mini" onclick="addGoal(${g.id})">+ Goal</button></div><div class="note-list">${g.goals.length?g.goals.map(x=>`<div class="note"><label class="check"><input type="checkbox" ${x.done?'checked':''} onchange="toggleGoal(${g.id},${x.id},this.checked)"><span style="text-decoration:${x.done?'line-through':'none'}">${esc(x.text)}</span></label></div>`).join(''):'<div class="muted">No goals yet.</div>'}</div><div class="section-head"><h2>Notes</h2><button class="mini" onclick="addNote(${g.id})">+ Note</button></div><div class="note-list">${g.notes.length?g.notes.map(n=>`<div class="note"><b>${esc(n.title)}</b><span class="muted">${esc(n.body)}</span><div style="margin-top:10px"><button class="mini" onclick="deleteNote(${g.id},${n.id})">Delete</button></div></div>`).join(''):'<div class="muted">No notes yet.</div>'}</div></div>`}
function setProgress(gid,v){games.find(g=>g.id===gid).progress=+v;save();openGame(gid)}
function addGoal(gid){const text=prompt('Tên mục tiêu:');if(!text?.trim())return;games.find(g=>g.id===gid).goals.push({id:id(),text:text.trim(),done:false});save();openGame(gid)}
function toggleGoal(gid,xid,v){const g=games.find(x=>x.id===gid),x=g.goals.find(x=>x.id===xid);x.done=v;const total=g.goals.length;g.progress=total?Math.round(g.goals.filter(x=>x.done).length/total*100):0;save();openGame(gid)}
function addNote(gid){const title=prompt('Tiêu đề note:');if(!title?.trim())return;const body=prompt('Nội dung:')??'';games.find(g=>g.id===gid).notes.push({id:id(),title:title.trim(),body});save();openGame(gid)}
function deleteNote(gid,nid){if(!confirm('Xóa note này?'))return;let g=games.find(x=>x.id===gid);g.notes=g.notes.filter(n=>n.id!==nid);save();openGame(gid)}
function deleteGame(gid){if(!confirm('Xóa game và toàn bộ note/goal của game này?'))return;games=games.filter(g=>g.id!==gid);save();document.getElementById('title').textContent='My Games';view='games';render()}
function editGame(gid){const g=games.find(x=>x.id===gid);editingId=gid;document.getElementById('modalTitle').textContent='Edit game';document.getElementById('gameName').value=g.name;document.getElementById('gameTag').value=g.tag;document.getElementById('modal').classList.add('show')}
function newGameModal(){editingId=null;document.getElementById('modalTitle').textContent='Add game';document.getElementById('gameName').value='';document.getElementById('gameTag').value='';document.getElementById('modal').classList.add('show');document.getElementById('gameName').focus()}
function closeModal(){document.getElementById('modal').classList.remove('show')}
function saveGame(){const name=document.getElementById('gameName').value.trim();if(!name)return toast('Nhập tên game trước nhé');let tag=(document.getElementById('gameTag').value.trim()||name.slice(0,3)).toUpperCase();if(editingId){const g=games.find(x=>x.id===editingId);g.name=name;g.tag=tag;toast('Đã cập nhật game')}else{games.push({id:id(),name,tag,progress:0,notes:[],goals:[]});toast('Đã thêm game')}save();closeModal();render()}
function notesView(list){const a=[];list.forEach(g=>g.notes.forEach(n=>a.push({...n,game:g.name,gid:g.id})));document.getElementById('content').innerHTML=`<div class="note-list">${a.length?a.map(n=>`<div class="note"><b>${esc(n.title)}</b><div class="muted">${esc(n.game)}</div><p>${esc(n.body)}</p><button class="mini" onclick="openGame(${n.gid})">Open game</button></div>`).join(''):'<div class="empty">No notes yet.</div>'}</div>`}
function goalsView(list){const a=[];list.forEach(g=>g.goals.forEach(x=>a.push({...x,game:g.name,gid:g.id})));document.getElementById('content').innerHTML=`<div class="note-list">${a.length?a.map(x=>`<div class="note"><label class="check"><input type="checkbox" ${x.done?'checked':''} onchange="toggleGoal(${x.gid},${x.id},this.checked)"><span style="text-decoration:${x.done?'line-through':'none'}"><b>${esc(x.text)}</b><small class="muted">${esc(x.game)}</small></span></label></div>`).join(''):'<div class="empty">No goals yet.</div>'}</div>`}
function exportData(){const blob=new Blob([JSON.stringify({app:'Game Note',version:2,games},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='game-note-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Đã export backup')}
function importData(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result),data=Array.isArray(d)?d:d.games;if(!Array.isArray(data))throw 0;games=data;save();render();toast('Đã import dữ liệu')}catch{toast('File JSON không hợp lệ')}};r.readAsText(file)}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('title').textContent=view==='games'?'My Games':view==='notes'?'All Notes':'Goals';render()});
document.getElementById('search').oninput=render;document.getElementById('addGameBtn').onclick=newGameModal;document.getElementById('closeModal').onclick=closeModal;document.getElementById('cancelBtn').onclick=closeModal;document.getElementById('saveGameBtn').onclick=saveGame;document.getElementById('exportBtn').onclick=exportData;document.getElementById('importBtn').onclick=()=>document.getElementById('fileInput').click();document.getElementById('fileInput').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);
render();